add pipeline stage to deploy Cfn template

diff --git a/pipeline.yaml b/pipeline.yaml
--- a/pipeline.yaml
+++ b/pipeline.yaml
@@ -1,5 +1,5 @@
 AWSTemplateFormatVersion: 2010-09-09
-Description: CodePipeline uses CodeBuild and GitHub
+Description: CodePipeline uses CodeBuild and GitHub - demo helloworld pipeline
 
 Parameters:
 
@@ -28,12 +28,13 @@ Parameters:
     Description: Choose the name for the bucket that will store the pipeline artifacts
     Default: sharina-pipeline-demo-artifacts
 
-  # SandboxAccountId:
-  #   Type: String
-  #   Description: AWS Account Id
-  #   MaxLength: 12
-  #   MinLength: 12
-  #   Default: "842337631775"
+  ProductName:
+    Type: String
+
+  DeployRegion:
+    Type: String
+    Default: us-west-2
+
 
 Resources:
 
@@ -70,12 +71,142 @@ Resources:
                 python: 3.7
             build:
               commands:
-                - echo "Hello World"
                 - echo "Checking current working directory"
                 - ls
+
+  CodeBuildCfnNagScan:
+    Type: AWS::CodeBuild::Project
+    Properties:
+      Name: CodeBuild-CfnNag-Scan
+      Description: Independent CfnNag scan project for post build artifacts
+      Artifacts:
+        Type: CODEPIPELINE
+      EncryptionKey: !GetAtt CMKKeyForPipeline.Arn
+      Environment:
+        Type: LINUX_CONTAINER
+        ComputeType: BUILD_GENERAL1_SMALL
+        Image: aws/codebuild/standard:2.0
+      LogsConfig:
+        CloudWatchLogs:
+          Status: "ENABLED"
+      ServiceRole: !GetAtt DemoPipelineCodeBuildRole.Arn
+      TimeoutInMinutes: 10
+      Source:
+        Type: CODEPIPELINE # specifies the source code settings for the project, such as the source code's repository type and location - source code placed in S3 bucket.
+        BuildSpec: |
+          version: 0.2
+          phases:
+            install:
+              runtime-versions:
+                ruby: 2.6
+              commands:
+                - echo "Installing cfn_nag utility - `pwd`"
+                - gem install cfn-nag
+                - cfn_nag -v
+                - echo "cfn_nag utility installation complete `date`"
+            build:
+              commands:
+                - echo "Starting cfn_nag scanning `date` in `pwd`"
+                - for y in `find deployment/dist/* -name "*.template"`; do echo "============= $y ================" ; cfn_nag --fail-on-warnings $y || ec1=$?; done
+                - if [ "$ec1" -ne "0" ]; then echo 'ERROR-1'; else echo 'SUCCESS-1'; ec1=0; fi
+                - echo "Exit Code 1 `echo $ec1`"
+                - for y in `find deployment/global-s3-assets/* -name "*.template"`; do echo "============= $y ================" ; cfn_nag --fail-on-warnings $y || ec2=$?; done
+                - if [ "$ec2" -ne "0" ]; then echo 'ERROR-2'; else echo 'SUCCESS-2'; ec2=0; fi
+                - echo "Exit Code 2 `echo $ec2`"
+                - echo "Completed cfn_nag scanning `date`"
+                - echo "Analyze exit codes and exit"
+                - if [ "$ec1" -ne "0" ] || [ "$ec2" -ne "0" ]; then echo 'ERROR'; ec=1; else echo 'SUCCESS'; ec=0; fi;
+                - echo "Exit Code Final `echo $ec`"
+                - exit $ec
           artifacts:
             files:
               - '**/*'
+
+  DeployCodePipelineCloudformationLogGroup:
+    Type: AWS::Logs::LogGroup
+    Properties:
+      LogGroupName: CodeBuildDeployCloudformationDemoLogGroup
+      RetentionInDays: 30
+
+  CodeBuildDeployCFnS3Bucket:
+    Type: AWS::CodeBuild::Project
+    Properties:
+      Name: DeployCloudFormationTemplate
+      Description: Deploys an S3 bucket with CloudFormation stack
+      ServiceRole: !GetAtt DemoPipelineCodeBuildRole.Arn
+      TimeoutInMinutes: 60
+      Artifacts:
+        Type: CODEPIPELINE
+      Environment:
+        Type: LINUX_CONTAINER
+        ComputeType: BUILD_GENERAL1_SMALL
+        Image: aws/codebuild/docker:18.09.0
+        PrivilegedMode: true
+        EnvironmentVariables:
+          - Name: ROLE
+            Value: ""
+          - Name: DEPLOY_REGION
+            Value: ""
+          - Name: TEMPLATE_FILE
+            Value: ""
+          - Name: PARAMETER_FILE
+            Value: ""
+          - Name: STACKPREFIX
+            Value: ""
+      LogsConfig:
+        CloudWatchLogs:
+          Status: ENABLED
+          GroupName: !Ref DeployCodePipelineCloudformationLogGroup
+      Source:
+        Type: CODEPIPELINE
+        BuildSpec: !Sub |
+          version: 0.2
+          phases:
+            install:
+              commands:
+                - sudo apt-get update
+                - sudo apt-get -y install unzip jq
+            pre_build:
+              commands:
+                - PRODUCTNAME=${ProductName}
+                - STACKNAME=$PRODUCTNAME$STACKPREFIX
+                - printenv
+                - ls -lha
+                - cp $TEMPLATE_FILE template.yaml
+                - test -z $PARAMETER_FILE || cp $PARAMETER_FILE parameters.json
+                - TOKEN=$(aws ssm get-parameter --name GithubPersonalToken --with-decryption --region ${DeployRegion} | jq -r '.Parameter.Value')
+                - sed -i "s/PLACEHOLDER/$TOKEN/g" parameters.json
+            build:
+              commands:
+                - DEPLOY_CREDENTIALS=$(aws sts assume-role --role-arn $ROLE --role-session-name codebuild-session)
+                - export AWS_ACCESS_KEY_ID=$(echo $DEPLOY_CREDENTIALS | jq .Credentials.AccessKeyId | xargs)
+                - export AWS_SECRET_ACCESS_KEY=$(echo $DEPLOY_CREDENTIALS | jq .Credentials.SecretAccessKey | xargs)
+                - export AWS_SESSION_TOKEN=$(echo $DEPLOY_CREDENTIALS | jq .Credentials.SessionToken | xargs)
+                - aws cloudformation describe-stacks --region $DEPLOY_REGION --stack-name $STACKNAME > describe_stack.log || true
+                - |
+                  if [ -s describe_stack.log ] && [ "$(jq -r .Stacks[0].StackStatus describe_stack.log)" = "ROLLBACK_COMPLETE" ]; then
+                  echo "Old stack is in \"ROLLBACK_COMPLETE\" state. Deleting old stack"
+                  aws cloudformation delete-stack --stack-name $STACKNAME --region $DEPLOY_REGION
+                  aws cloudformation wait stack-delete-complete --stack-name $STACKNAME --region $DEPLOY_REGION
+                  fi
+                - TIMESTAMP=$(date -u "+%Y-%m-%dT%H:%M:%S")
+                - >
+                  aws cloudformation deploy --template-file template.yaml \
+                      --capabilities CAPABILITY_NAMED_IAM \
+                      --role-arn $ROLE \
+                      --stack-name $STACKNAME \
+                      --region $DEPLOY_REGION \
+                      --no-fail-on-empty-changeset \
+                      --parameter-overrides file://parameters.json ||
+                      (aws cloudformation describe-stack-events \
+                          --stack-name $STACKNAME \
+                          --output table \
+                          --region $DEPLOY_REGION \
+                          --query "StackEvents[?Timestamp >= \`$TIMESTAMP\`].[Timestamp,ResourceType,LogicalResourceId,ResourceStatus,ResourceStatusReason]" && false)
+            post_build:
+              commands:
+                - aws cloudformation describe-stacks --stack-name $STACKNAME --query 'Stacks[*].Outputs' | jq '.[]' > ./cloudformation-outputs.json
+
 
   #------- CodePipeline -------
   DemoPipeline:
@@ -105,6 +236,7 @@ Resources:
               OutputArtifacts: # This option can only be used by CodeBuild downstream actions.
                 - Name: SourceOutput
               RunOrder: 1
+
         - Name: HelloWorld
           Actions:
             - Name: DirectoryListHelloWorld
@@ -118,8 +250,62 @@ Resources:
               RunOrder: 1
               InputArtifacts:
                 - Name: SourceOutput
+
+        - Name: CfnNagScan
+          Actions:
+            - Name: CfnNagScan
+              ActionTypeId:
+                Category: Build
+                Owner: AWS
+                Version: '1'
+                Provider: CodeBuild
+              Configuration:
+                ProjectName: !Ref CodeBuildCfnNagScan
+              RunOrder: 1
+              InputArtifacts:
+                - Name: SourceOutput
               OutputArtifacts:
-                - Name: AccountListOutput
+                - Name: CfnNagScanArtifact
+
+        - Name: DeployCFnS3BucketToDev
+          Actions:
+            - Name: DeployCloudFormationS3Bucket
+              ActionTypeId:
+                Category: Build
+                Owner: AWS
+                Version: "1"
+                Provider: CodeBuild
+              Configuration:
+                ProjectName: !Ref CodeBuildDeployCFnS3Bucket
+                EnvironmentVariables: !Sub |
+                  [
+                    {
+                      "name": "ROLE",
+                      "value": "arn:aws:iam::842337631775:role/DeploymentRole"
+                    },
+                    {
+                      "name": "DEPLOY_REGION",
+                      "value": "${DeployRegion}"
+                    },
+                    {
+                      "name": "TEMPLATE_FILE",
+                      "value": "./s3-bucket.yaml"
+                    },
+                    {
+                      "name": "PARAMETER_FILE",
+                      "value": "./parameters/${DeployRegion}.json"
+                    },
+                    {
+                      "name": "STACKPREFIX",
+                      "value": "sharina-"
+                    }
+                  ]
+              RunOrder: 2
+              InputArtifacts:
+                - Name: SourceOutput
+
+
+
 
   #------- Encryption -------
   CMKKeyForPipeline:
@@ -258,12 +444,6 @@ Resources:
               - kms:DescribeKey,
               - kms:CreateGrant
             Resource: "*"
-          # - Sid: AssumeRolePermissions
-          #   Effect: Allow
-          #   Action:
-          #     - sts:AssumeRole
-          #   Resource:
-          #     - "arn:aws:iam::*:role/DeploymentRole"
 
   DemoPipelineRole:
     Type: AWS::IAM::Role
@@ -279,7 +459,7 @@ Resources:
               - sts:AssumeRole
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
-        - arn:aws:iam::aws:policy/AmazonS3FullAccess #TODO: Remove
+        - arn:aws:iam::aws:policy/AmazonS3FullAccess
         - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
         - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
       Path: /
@@ -300,31 +480,7 @@ Resources:
               - codebuild:StartBuild
             Resource:
               - "*"
-          # - Effect: Allow #TODO: Remove
-          #   Action:
-          #     - lambda:InvokeFunction
-          #   Resource:
-          #     - "*"
       Roles:
         - !Ref DemoPipelineRole
 
-  # DeploymentRole: #TODO: test this
-  #   Type: AWS::IAM::Role
-  #   Properties:
-  #     RoleName: DeploymentRole
-  #     AssumeRolePolicyDocument:
-  #       Version: 2012-10-17
-  #       Statement:
-  #         - Effect: Allow
-  #           Principal:
-  #             Service:
-  #               - cloudformation.amazonaws.com
-  #               - codepipeline.amazonaws.com
-  #             AWS:
-  #               - !Sub arn:aws:iam::${SandboxAccountId}:root
-  #           Action:
-  #             - sts:AssumeRole
-  #     Path: /
-  #     ManagedPolicyArns:
-  #       - arn:aws:iam::aws:policy/AdministratorAccess
 
